### ISSUE TITLE
Doesn't install on Linux

### ISSUE THREAD

**Issue by 222464** [MarcoMeter/drl-memory-gym#5]
Hi,

In order to install on Linux, this line needs to be changed to not have backwards slashes (Windows) but a forward slash.

https://github.com/MarcoMeter/drl-memory-gym/blob/26c50a052a631d3c11c41a40e75c13cd34141d10/setup.py#L11

**Comment by MarcoMeter** [comment]
Thanks, I fixed this. This was only concerned with installing memory-gym from source. The PyPi package is not affected.
