### ISSUE TITLE
Support for Gymnasium >=v0.26.3

### ISSUE THREAD

**Issue by subho406** [MarcoMeter/drl-memory-gym#6]
Hi,

Is there a reason only Gymnasium v0.26.3 is supported? Is it possible to remove this requirement and support for newer versions of gymnasium by any chance?

Thanks

**Comment by MarcoMeter** [comment]
We did not test v 0.27.* yet, but will do so soon. The changelog does not seem to yield any breaking changes towards Memory Gym.

**Comment by MarcoMeter** [comment]
We finally released the next version of Memory Gym (featuring endless environments). `gymnasium==0.29.0` is supported.
